image: node:12.13.0-alpine
stages:
  - build
  - deploy

#Build
build:
  stage: build
  script:
    - cd frontend
    - yarn install
    - yarn run build

before_script:
  - yarn global add firebase-tools

deploy:
  stage: deploy
  script:
    - cd frontend
    - yarn install
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    - dev
