cache:

image: node:12.13.0-alpine
stages:
  - build
  - ktlint
  - lint
  - deploy

ktlint:
  image: openjdk:14-ea-8-jdk-alpine3.10
  stage: ktlint
  
  script:
    - cd backend
    - ./gradlew ktlintCheck

lint:
  stage: lint
  script:
    - cd frontend
    - yarn add eslint
    - node_modules/eslint/bin/eslint.js

#Build
build:
  stage: build
  script:
    - cd frontend
    - yarn install
    - yarn run build


deploy:
  stage: deploy
  script:
    - yarn global add firebase-tools	
    - cd frontend
    - yarn install
    - yarn run build
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    - dev
