image: node:12.13.0-alpine
stages:
  - build
  - deploy

#Build
build:
  stage: build
  script:
    - cd frontend
    - yarn install
    - yarn run build


Job deploying

before_script:
  - yarn install -g firebase-tools

deploy:
  stage: deploy
 script:
  - cd frontend/src
  - yarn install
  - cd ..
  - firebase deploy --token $FIREBASE_TOKEN
only:
  - dev
