version: '3'

services:
  # db:
  #   image: mysql:5.7
  #   container_name: db
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_USER=dev
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_DATABASE=group-generation
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - '8080:80'
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: ./gradlew run
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    # depends_on:
    #   - db